### ISSUE TITLE
Create a program to check for a duplicate element

### ISSUE THREAD

**Issue by hitaarthh** [hitaarthh/C-Programming#1]
Write a C program to find duplicate elements in an integer array. Return the index of the duplicate elements if found else return -1.

Example:

```C
int arr[5] = {1,2,2,3,4};
```
so here the integer 2 is repeated, hence it will return index 1 and 2.

You can access the files here: https://github.com/hitaarthh/C-Basics/blob/main/duplicateElement.c

**Comment by Suraksha-Rajagopalan** [comment]
@hitaarthh Can u assign me for this issue?

**Comment by hitaarthh** [comment]
@Suraksha-Rajagopalan Yes, you may proceed.

**Comment by Suraksha-Rajagopalan** [comment]
Pushed the necessary changes. #2
