### ISSUE TITLE
Make use of functions to find the duplicity of a number

### ISSUE THREAD

**Issue by hitaarthh** [hitaarthh/C-Programming#3]
Make appropriate use of functions and function calling to check the duplicity of an integer value.

Access the files at: https://github.com/hitaarthh/C-Basics/blob/main/duplicateElement.c

**Comment by Suraksha-Rajagopalan** [comment]
@hitaarthh I would like work on this issue, Can you assign it to me?

**Comment by sid172014** [comment]
Assign it to me , i would like to work on this ....

**Comment by hitaarthh** [comment]
@Suraksha-Rajagopalan You may proceeed.

**Comment by hitaarthh** [comment]
@sid172014 you may look into my other repositories for issues, that might potentially help you to contribute.

**Comment by Suraksha-Rajagopalan** [comment]
#4
The necessary changes have been made.
